### ISSUE TITLE
Getting the model after training

### ISSUE THREAD

**Issue by Malkiz** [nicolaspanel/node-svm#30]
I would like a way to get the actual model after the training was done. This way it can be saved and loaded, instead of having to train it again every time I run my code.
Also, it can be used to construct a "formula" or algorithm for classification based on the model, which can run in JS, and therefore be available in any JS environment including the browsers.

**Comment by nicolaspanel** [comment]
See [this example](https://github.com/nicolaspanel/node-svm/blob/master/examples/save-prediction-model-example.js) for more info on how to retrieve/load a model. Since models are dictionaries (JS object) you can save it to JSON if needed.

Please note that this library is a nodejs addon therefore it cannot be used in the browser.
Best regards

**Comment by Malkiz** [comment]
Great, thanks!
